"""Durable worker for turning a saved fish catch into one B-side card.

The worker deliberately orchestrates the already-approved visual services.  It
does not contain a second fish, pose, outline, or background implementation.
"""

from __future__ import annotations

import os
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from google.cloud import storage
from sqlalchemy import select
from sqlalchemy.orm import Session

from app.db import SessionLocal
from app.factory import DOWNLOAD_RETRY, get_bucket_name
from app.models import FishBsideJob, FishCatch
from app.platform.models import PlatformOperationLog
from app.platform.services.bside_assets import read_bside_uri
from app.platform.services.bside_visual import compose_bside, outline, standardize
from app.platform.services.bside_visual.asset_registry import (
    background_water_template,
    outline_renderer_style,
    select_active_bside_style_plan,
)
from app.platform.services.qwen_output import process_qwen_output


PENDING = "PENDING"
PROCESSING = "PROCESSING"
SUCCESS = "SUCCESS"
FAILED = "FAILED"
_WORKER_POOL = ThreadPoolExecutor(max_workers=max(1, int(os.getenv("BSIDE_JOB_WORKERS", "2"))))


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


def _object_name(job: FishBsideJob, filename: str) -> str:
    return f"fish-bside/{job.user_id}/{job.fish_record_id}/{job.id}/{filename}"


def _store_job_asset(job: FishBsideJob, filename: str, data: bytes, media_type: str) -> tuple[str, str]:
    """Store generated bytes in the existing bucket, with the test fallback.

    B-side production always uses GCS because a saved catch itself lives
    there.  The local path keeps direct unit tests independent from cloud
    credentials and follows the established B-side-demo fallback convention.
    """

    object_name = _object_name(job, filename)
    try:
        bucket_name = get_bucket_name()
    except RuntimeError:
        path = Path("/tmp") / "yujian" / object_name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
        return str(path), object_name
    try:
        storage.Client().bucket(bucket_name).blob(object_name).upload_from_string(
            data,
            content_type=media_type,
        )
    except Exception as exc:
        raise RuntimeError(f"B 面结果保存失败：{exc}") from exc
    return f"gs://{bucket_name}/{object_name}", object_name


def _read_catch_image(row: FishCatch) -> tuple[bytes, str]:
    object_name = str(row.image_object_name or "").strip()
    if not object_name:
        raise RuntimeError("鱼获原图路径不存在")
    try:
        bucket_name = get_bucket_name()
    except RuntimeError:
        path = Path(object_name)
        if not path.is_file():
            raise RuntimeError("鱼获原图不存在")
        return path.read_bytes(), str(path)
    try:
        blob = storage.Client().bucket(bucket_name).blob(object_name)
        if not blob.exists():
            raise RuntimeError("鱼获原图不存在")
        return blob.download_as_bytes(timeout=120, retry=DOWNLOAD_RETRY), f"gs://{bucket_name}/{object_name}"
    except RuntimeError:
        raise
    except Exception as exc:
        raise RuntimeError(f"鱼获原图暂时无法读取：{exc}") from exc


def _log(db: Session, job: FishBsideJob, operation: str, *, status: str, message: str = "", detail: dict[str, Any] | None = None) -> None:
    import json

    db.add(
        PlatformOperationLog(
            operation_type=operation,
            resource_type="fish_bside_job",
            resource_id=job.id,
            status=status,
            message=message or None,
            detail_json=json.dumps(detail or {}, ensure_ascii=False, separators=(",", ":")),
            actor=f"user:{job.user_id}",
        )
    )


def _claim_job(db: Session, job_id: str) -> tuple[FishBsideJob, FishCatch] | None:
    """Atomically move a durable pending job to PROCESSING exactly once."""

    job = db.scalar(
        select(FishBsideJob)
        .where(FishBsideJob.id == str(job_id))
        .with_for_update()
    )
    if job is None or job.status != PENDING:
        return None
    record = db.get(FishCatch, job.fish_record_id)
    if record is None:
        job.status = FAILED
        job.error_code = "FISH_RECORD_MISSING"
        job.error_message = "鱼获记录不存在"
        job.completed_at = _utcnow()
        _log(db, job, "BSIDE_JOB_FAILED", status=FAILED, message=job.error_message)
        db.commit()
        return None
    job.status = PROCESSING
    job.started_at = _utcnow()
    job.error_code = None
    job.error_message = None
    record.bside_status = "GENERATING"
    _log(db, job, "BSIDE_JOB_STARTED", status=PROCESSING)
    db.commit()
    return job, record


def process_fish_bside_job(job_id: str) -> None:
    """Run one claimed job in a fresh database session.

    It is safe to dispatch the same job more than once: only its first
    PENDING claim reaches the pipeline.  A failed job is never silently
    retried; the user explicitly requests a new attempt from the app.
    """

    db = SessionLocal()
    try:
        claimed = _claim_job(db, job_id)
        if claimed is None:
            return
        job, record = claimed
        try:
            source, input_uri = _read_catch_image(record)
            job.input_image_uri = input_uri

            transparent = process_qwen_output(source).transparent_fish
            job.transparent_fish_uri, _ = _store_job_asset(
                job, "transparent_fish_rgba.png", transparent, "image/png"
            )

            standardized = standardize(transparent)
            job.standardized_fish_uri, _ = _store_job_asset(
                job, "standardized_fish_rgba.png", standardized.data, standardized.media_type
            )

            plan = select_active_bside_style_plan(db, style_seed=job.style_seed)
            background = plan["background"]
            outline_style = plan["outline_style"]
            profile = plan["profile"]
            job.background_id = background.id
            job.outline_style_id = outline_style.id
            job.outline_profile_id = profile.id
            job.style_seed = int(plan["style_seed"])

            styled = outline(standardized.data, outline_renderer_style(outline_style, profile))
            job.outlined_fish_uri, _ = _store_job_asset(
                job, "outlined_fish_rgba.png", styled.data, styled.media_type
            )

            background_bytes, _ = read_bside_uri(str(background.background_uri))
            foreground_bytes = read_bside_uri(str(background.foreground_uri))[0] if background.foreground_uri else None
            light_bytes = read_bside_uri(str(background.light_uri))[0] if background.light_uri else None
            composed = compose_bside(
                standardized.data,
                outline_renderer_style(outline_style, profile),
                background_water_template(background, fish_width_ratio=float(plan["fish_width_ratio"])),
                outlined_fish=styled.data,
                background_bytes=background_bytes,
                foreground_bytes=foreground_bytes,
                light_bytes=light_bytes,
            )
            job.result_uri, job.result_object_name = _store_job_asset(
                job, "bside_result.png", composed["master"], "image/png"
            )
            job.status = SUCCESS
            job.completed_at = _utcnow()
            record.bside_status = "READY"
            record.bside_result_uri = job.result_uri
            record.bside_result_object_name = job.result_object_name
            record.bside_generated_at = job.completed_at
            record.bside_job_id = job.id
            _log(
                db,
                job,
                "BSIDE_JOB_SUCCESS",
                status=SUCCESS,
                detail={
                    "background_id": job.background_id,
                    "outline_style_id": job.outline_style_id,
                    "result_uri": job.result_uri,
                },
            )
            db.commit()
        except Exception as exc:
            db.rollback()
            failed_job = db.get(FishBsideJob, job_id)
            if failed_job is None:
                return
            failed_record = db.get(FishCatch, failed_job.fish_record_id)
            code = getattr(exc, "code", None) or "BSIDE_PIPELINE_FAILED"
            message = getattr(exc, "message", None) or str(exc) or "B 面生成失败"
            failed_job.status = FAILED
            failed_job.error_code = str(code)[:128]
            failed_job.error_message = str(message)
            failed_job.completed_at = _utcnow()
            if failed_record is not None:
                failed_record.bside_status = "FAILED"
                failed_record.bside_job_id = failed_job.id
            _log(db, failed_job, "BSIDE_JOB_FAILED", status=FAILED, message=str(message), detail={"error_code": str(code)})
            db.commit()
    finally:
        db.close()


def enqueue_fish_bside_job(job_id: str) -> None:
    """Submit one already-persisted job without keeping the API request busy."""

    _WORKER_POOL.submit(process_fish_bside_job, str(job_id))


def recover_pending_bside_jobs(*, limit: int = 20) -> int:
    """Re-dispatch durable work after an app restart.

    A process can disappear while rendering an image. Jobs that exceeded the
    bounded processing lease return to PENDING; all still-pending work is then
    submitted to the local V1 worker pool. The worker claim prevents duplicate
    execution when more than one app instance observes the same row.
    """

    from datetime import timedelta

    lease_seconds = max(60, int(os.getenv("BSIDE_JOB_PROCESSING_LEASE_SECONDS", "1800")))
    cutoff = _utcnow() - timedelta(seconds=lease_seconds)
    db = SessionLocal()
    try:
        stale = db.scalars(
            select(FishBsideJob).where(
                FishBsideJob.status == PROCESSING,
                FishBsideJob.started_at.is_not(None),
                FishBsideJob.started_at < cutoff,
            )
        ).all()
        for job in stale:
            job.status = PENDING
            job.started_at = None
            _log(db, job, "BSIDE_JOB_RECOVERED", status=PENDING, message="处理租约超时，已重新派发")
        if stale:
            db.commit()
        pending_ids = list(
            db.scalars(
                select(FishBsideJob.id)
                .where(FishBsideJob.status == PENDING)
                .order_by(FishBsideJob.created_at)
                .limit(max(1, min(int(limit), 100)))
            ).all()
        )
    finally:
        db.close()
    for pending_id in pending_ids:
        enqueue_fish_bside_job(str(pending_id))
    return len(pending_ids)


__all__ = [
    "FAILED",
    "PENDING",
    "PROCESSING",
    "SUCCESS",
    "enqueue_fish_bside_job",
    "process_fish_bside_job",
    "recover_pending_bside_jobs",
]
