"""Strict identity-transfer preprocessing for Image Studio V2.

This module intentionally keeps the strict head-swap geometry on the API side:
Google Cloud Vision locates the primary face, Pillow builds deterministic head
ROIs/masks, and Qwen edits only that ROI. Pixels outside the ROI are never
regenerated by the model.
"""

from __future__ import annotations

import io
from dataclasses import dataclass
from typing import Iterable

from google.cloud import vision
from PIL import Image, ImageDraw, ImageFilter


class IdentityPreprocessError(RuntimeError):
    def __init__(self, code: str, message: str) -> None:
        super().__init__(message)
        self.code = code


@dataclass(frozen=True)
class Box:
    left: int
    top: int
    right: int
    bottom: int

    @property
    def width(self) -> int:
        return max(1, self.right - self.left)

    @property
    def height(self) -> int:
        return max(1, self.bottom - self.top)

    @property
    def area(self) -> int:
        return self.width * self.height

    def as_list(self) -> list[int]:
        return [self.left, self.top, self.right, self.bottom]


@dataclass(frozen=True)
class StrictIdentityAssets:
    base_face_box: Box
    base_head_box: Box
    identity_face_box: Box
    identity_head_box: Box
    base_head_crop: bytes
    identity_face_crop: bytes
    identity_head_crop: bytes
    head_mask: bytes
    head_mask_preview: bytes
    angle_head_crop: bytes | None = None


_TIGHTNESS = {
    "TIGHT": {
        "x": 0.34,
        "top": 0.62,
        "bottom": 0.28,
        "mask_x": 0.07,
        "mask_top": 0.04,
        "mask_bottom": 0.08,
        "feather": 0.035,
    },
    "MEDIUM": {
        "x": 0.50,
        "top": 0.88,
        "bottom": 0.42,
        "mask_x": 0.04,
        "mask_top": 0.02,
        "mask_bottom": 0.06,
        "feather": 0.045,
    },
    "LOOSE": {
        "x": 0.68,
        "top": 1.08,
        "bottom": 0.58,
        "mask_x": 0.02,
        "mask_top": 0.01,
        "mask_bottom": 0.04,
        "feather": 0.055,
    },
}


def _open_rgb(data: bytes) -> Image.Image:
    with Image.open(io.BytesIO(data)) as source:
        return source.convert("RGB")


def _png(image: Image.Image) -> bytes:
    output = io.BytesIO()
    image.save(output, format="PNG")
    return output.getvalue()


def _clamp_box(box: Box, width: int, height: int) -> Box:
    left = max(0, min(int(box.left), max(0, width - 1)))
    top = max(0, min(int(box.top), max(0, height - 1)))
    right = max(left + 1, min(int(box.right), width))
    bottom = max(top + 1, min(int(box.bottom), height))
    return Box(left, top, right, bottom)


def _vertices_to_box(vertices: Iterable[object], width: int, height: int) -> Box | None:
    xs: list[int] = []
    ys: list[int] = []
    for vertex in vertices:
        x = int(getattr(vertex, "x", 0) or 0)
        y = int(getattr(vertex, "y", 0) or 0)
        xs.append(x)
        ys.append(y)
    if not xs or not ys:
        return None
    box = _clamp_box(Box(min(xs), min(ys), max(xs), max(ys)), width, height)
    if box.width < 8 or box.height < 8:
        return None
    return box


def detect_primary_face(
    image_bytes: bytes,
    *,
    label: str,
    client: vision.ImageAnnotatorClient | None = None,
) -> Box:
    image = _open_rgb(image_bytes)
    width, height = image.size
    detector = client or vision.ImageAnnotatorClient()
    response = detector.face_detection(
        image=vision.Image(content=image_bytes),
        max_results=5,
    )
    if getattr(response, "error", None) and getattr(response.error, "message", ""):
        raise IdentityPreprocessError(
            "HEAD_DETECTION_FAILED",
            f"{label} 人脸检测失败：{response.error.message}",
        )

    boxes: list[Box] = []
    for annotation in list(getattr(response, "face_annotations", []) or []):
        polygon = getattr(annotation, "fd_bounding_poly", None) or getattr(annotation, "bounding_poly", None)
        box = _vertices_to_box(getattr(polygon, "vertices", []) if polygon else [], width, height)
        if box is not None:
            boxes.append(box)

    if not boxes:
        code = "IDENTITY_FACE_NOT_FOUND" if label.startswith("identity") else "HEAD_DETECTION_FAILED"
        raise IdentityPreprocessError(code, f"{label} 未检测到可用人脸。")

    boxes.sort(key=lambda item: item.area, reverse=True)
    if len(boxes) > 1 and boxes[1].area >= boxes[0].area * 0.60:
        raise IdentityPreprocessError(
            "MULTIPLE_FACES_AMBIGUOUS",
            f"{label} 检测到多个主要人脸，无法确定目标人物。",
        )
    return boxes[0]


def expand_head_box(face: Box, image_size: tuple[int, int], *, tightness: str = "MEDIUM") -> Box:
    width, height = image_size
    key = str(tightness or "MEDIUM").strip().upper()
    params = _TIGHTNESS.get(key)
    if params is None:
        raise IdentityPreprocessError("INVALID_HEAD_TIGHTNESS", f"未知 head tightness: {tightness}")

    x_pad = face.width * params["x"]
    top_pad = face.height * params["top"]
    bottom_pad = face.height * params["bottom"]
    return _clamp_box(
        Box(
            int(round(face.left - x_pad)),
            int(round(face.top - top_pad)),
            int(round(face.right + x_pad)),
            int(round(face.bottom + bottom_pad)),
        ),
        width,
        height,
    )


def crop_png(image_bytes: bytes, box: Box) -> bytes:
    image = _open_rgb(image_bytes)
    clamped = _clamp_box(box, *image.size)
    return _png(image.crop(clamped.as_list()))


def build_head_mask(
    *,
    head_box: Box,
    face_box: Box,
    tightness: str = "MEDIUM",
) -> tuple[bytes, bytes]:
    """Return feathered ROI mask and visible preview mask, both ROI-sized PNGs."""

    key = str(tightness or "MEDIUM").strip().upper()
    params = _TIGHTNESS.get(key)
    if params is None:
        raise IdentityPreprocessError("INVALID_HEAD_TIGHTNESS", f"未知 head tightness: {tightness}")

    width, height = head_box.width, head_box.height
    rel_face = Box(
        face_box.left - head_box.left,
        face_box.top - head_box.top,
        face_box.right - head_box.left,
        face_box.bottom - head_box.top,
    )

    # The ellipse deliberately covers hair + face + a small neck transition,
    # but never extends to shoulders/body outside the head ROI.
    left = max(0, int(rel_face.left - face_box.width * (params["x"] + params["mask_x"])))
    right = min(width, int(rel_face.right + face_box.width * (params["x"] + params["mask_x"])))
    top = max(0, int(rel_face.top - face_box.height * (params["top"] + params["mask_top"])))
    bottom = min(height, int(rel_face.bottom + face_box.height * (params["bottom"] + params["mask_bottom"])))

    hard = Image.new("L", (width, height), 0)
    draw = ImageDraw.Draw(hard)
    draw.ellipse((left, top, right, bottom), fill=255)

    feather_px = max(3, int(round(min(width, height) * params["feather"])))
    soft = hard.filter(ImageFilter.GaussianBlur(radius=feather_px))

    preview = Image.new("RGBA", (width, height), (0, 0, 0, 0))
    overlay = Image.new("RGBA", (width, height), (255, 215, 128, 0))
    overlay.putalpha(hard.point(lambda value: 110 if value else 0))
    preview = Image.alpha_composite(preview, overlay)
    return _png(soft), _png(preview)


def prepare_strict_identity_assets(
    *,
    base_bytes: bytes,
    identity_bytes: bytes,
    angle_bytes: bytes | None = None,
    tightness: str = "MEDIUM",
    client: vision.ImageAnnotatorClient | None = None,
) -> StrictIdentityAssets:
    detector = client or vision.ImageAnnotatorClient()

    base_image = _open_rgb(base_bytes)
    identity_image = _open_rgb(identity_bytes)

    base_face = detect_primary_face(base_bytes, label="base", client=detector)
    identity_face = detect_primary_face(identity_bytes, label="identity_reference", client=detector)
    base_head = expand_head_box(base_face, base_image.size, tightness=tightness)
    identity_head = expand_head_box(identity_face, identity_image.size, tightness="MEDIUM")

    head_mask, preview = build_head_mask(
        head_box=base_head,
        face_box=base_face,
        tightness=tightness,
    )

    angle_crop: bytes | None = None
    if angle_bytes:
        angle_image = _open_rgb(angle_bytes)
        angle_face = detect_primary_face(angle_bytes, label="identity_angle", client=detector)
        angle_head = expand_head_box(angle_face, angle_image.size, tightness="MEDIUM")
        angle_crop = crop_png(angle_bytes, angle_head)

    return StrictIdentityAssets(
        base_face_box=base_face,
        base_head_box=base_head,
        identity_face_box=identity_face,
        identity_head_box=identity_head,
        base_head_crop=crop_png(base_bytes, base_head),
        identity_face_crop=crop_png(identity_bytes, identity_face),
        identity_head_crop=crop_png(identity_bytes, identity_head),
        head_mask=head_mask,
        head_mask_preview=preview,
        angle_head_crop=angle_crop,
    )


def composite_head_roi(
    *,
    base_bytes: bytes,
    edited_head_bytes: bytes,
    head_box: Box,
    roi_mask_bytes: bytes,
) -> bytes:
    base = _open_rgb(base_bytes)
    edited = _open_rgb(edited_head_bytes).resize(
        (head_box.width, head_box.height),
        Image.Resampling.LANCZOS,
    )
    with Image.open(io.BytesIO(roi_mask_bytes)) as mask_source:
        mask = mask_source.convert("L").resize(
            (head_box.width, head_box.height),
            Image.Resampling.LANCZOS,
        )

    original_roi = base.crop(head_box.as_list())
    blended = Image.composite(edited, original_roi, mask)
    result = base.copy()
    result.paste(blended, (head_box.left, head_box.top))
    return _png(result)


__all__ = [
    "Box",
    "IdentityPreprocessError",
    "StrictIdentityAssets",
    "build_head_mask",
    "composite_head_roi",
    "crop_png",
    "detect_primary_face",
    "expand_head_box",
    "prepare_strict_identity_assets",
]
