-- Add product-facing catch metadata and stable client idempotency.
-- Safe to reapply. Existing classifier_result_json, record IDs, image paths,
-- and fish_bside_job references are deliberately left untouched.

ALTER TABLE fish_catches ADD COLUMN IF NOT EXISTS length_cm DOUBLE PRECISION;
ALTER TABLE fish_catches ADD COLUMN IF NOT EXISTS weight_kg DOUBLE PRECISION;
ALTER TABLE fish_catches ADD COLUMN IF NOT EXISTS location TEXT;
ALTER TABLE fish_catches ADD COLUMN IF NOT EXISTS story TEXT;
ALTER TABLE fish_catches ADD COLUMN IF NOT EXISTS metadata_version INTEGER NOT NULL DEFAULT 0;
ALTER TABLE fish_catches ADD COLUMN IF NOT EXISTS client_record_id VARCHAR(128);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_fish_catches_length_cm_range') THEN
        ALTER TABLE fish_catches ADD CONSTRAINT ck_fish_catches_length_cm_range
            CHECK (length_cm IS NULL OR (length_cm > 0 AND length_cm <= 1000)) NOT VALID;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_fish_catches_weight_kg_range') THEN
        ALTER TABLE fish_catches ADD CONSTRAINT ck_fish_catches_weight_kg_range
            CHECK (weight_kg IS NULL OR (weight_kg > 0 AND weight_kg <= 1000)) NOT VALID;
    END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS uq_fish_catches_user_client_record
    ON fish_catches (user_id, client_record_id)
    WHERE client_record_id IS NOT NULL;

-- Read-only recovery audit: summarize rows without exposing values in logs.
-- Detailed recordId/field proposals are generated by scripts/audit_catch_metadata.py.
-- This query is intentionally not an UPDATE; production backfill remains a
-- separately reviewed operation after matching only within each recordId.
